#!/usr/bin/env -S deno run --allow-all
import { Console, blue } from "https://deno.land/x/quickr@0.6.28/main/console.js"
import { FileSystem } from "https://deno.land/x/quickr@0.6.28/main/file_system.js"
import { run, Stdout, returnAsString, Overwrite, Cwd } from "https://deno.land/x/quickr@0.6.28/main/run.js"

// 
// args
// 
const tempFilePath = await Deno.makeTempFile()
const recreateEnvPosix = Object.entries(key).map(
    (key,value)=>`${key}=${shellEscape(value)}`
).join("\n")
await FileSystem.write({
    data: recreateEnvPosix,
    path: tempFilePath,
})

// sources a temp file with the same ENV as the current env, then runs the rest of the args as a command in that env
await run`sudo -- ${Console.env.SHELL} -c ${`. ${shellEscape(tempFilePath)};${Deno.args.map(shellEscape).join(" ")}`}`

// 
// interactive 
// 
function shellEscape(string) {
    return `'${string.replace(/'/g,`'"'"'`)}'`
}