#!/usr/bin/env -S deno run --allow-all
import { Console, blue } from "https://deno.land/x/quickr@0.3.14/main/console.js"
import { FileSystem } from "https://deno.land/x/quickr@0.3.14/main/file_system.js"
import { run, Stdout, returnAsString, Overwrite, Cwd } from "https://deno.land/x/quickr@0.3.14/main/run.js"

// 
// args
// 
let [ fileOrFolder ] = Deno.args

// 
// interactive 
// 
const info = await FileSystem.info(fileOrFolder)
if (info.doesntExist) {
    throw Error(`File/Folder doesnt seem to exist: ${fileOrFolder}`)
}
if (info.isFolder) {
    const newPath = `${file}.tar`
    await FileSystem.clearAPathFor(newPath)
    const {success} = await run`tar cz ${fileOrFolder} ${Stdout(Overwrite(newPath))}`.outcome
    if (!success) {
        throw Error(`Failed to tar file`)
    }
    fileOrFolder = newPat
}

const outputPath = `${fileOrFolder}.enc`
await FileSystem.clearAPathFor(outputPath)
const {success} = await run`gpg -c ${Stdout(Overwrite(outputPath))}`.outcome