#!/usr/bin/env bash

set -euo pipefail

git for-each-ref \
  --sort=committerdate \
  --format='%(committerdate:iso8601)%09%(refname:short)' \
  refs/heads refs/remotes \
  | awk -F '\t' '$2 !~ /\/HEAD$/ { print $1 "  " $2 }'
