#!/usr/bin/env bash
remote_name="$1"
remote_url="$2"
if [ -z "$remote_name" ]; then
    echo "what should the upstream source be called?"
    read remote_name
fi
if [ -z "$remote_url" ]; then
    echo "what is the url to the upstream source?"
    read remote_url
fi
git remote add "$remote_name" "$remote_url"
