#!/usr/bin/env bash
name="$1"
url="$2"
branch="${3:-master}"
git remote add "@$name" "$url"
git fetch "@$name" "$branch"
git checkout -b "@$name/$branch" "remotes/@$name/$branch"
echo "new branch is named: @$name/$branch"
