#!/usr/bin/env bash
new_branch_name="$1"
target_folder="$2"
if ! [ -d ".git" ]; then
    echo "need to be in the same directory as the .git folder"
    exit 1
fi
if ! [ -d "$target_folder" ]; then
    echo "second argument needs to be a folder that you want to be a branch"
    exit 1
fi
target_folder="$(cd "$(dirname "$target_folder")"; pwd)/$(basename "$target_folder")"
mkdir -p ./.cache/tmp/brancher
cp -r ".git" "./.cache/tmp/brancher/.git"
touch "./.cache/tmp/brancher/.keep"
cd "./.cache/tmp/brancher/"
git checkout --orphan "$new_branch_name"
git add -A
git commit -m "init"
git push --set-upstream origin "$new_branch_name"
cp -R "$target_folder"/. .
git add -A
git commit -m "first real branch commit"
git push
cd ../../..
git fetch origin "$new_branch_name"
rm -rf "./.cache/tmp"
