#!/usr/bin/env bash

# if apt-get exists and if curl not exists
if [ -n "$(command -v "apt-get")" ] && [ -n "$(command -v "curl")" ]
then
    sudo apt-get update -y 
    sudo apt-get install -y curl
fi

# install nix
. <(curl -fsSL https://raw.githubusercontent.com/jeff-hykin/fornix/master/settings/extensions/nix/installer_helper)

# install deno
nix-env -i deno-1.17.1 -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz


export NIXPKGS_ALLOW_UNFREE=1

#
# installing basic tools
#
nix-env -iA nixpkgs.git
nix-env -iA nixpkgs.dua    # for cleaning disk space
nix-env -iA nixpkgs.curl
nix-env -iA nixpkgs.fd     # for finding things
nix-env -iA nixpkgs.bottom # "btm" better than top
nix-env -iA nixpkgs.vscode
nix-env -i ssh-copy-id -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz  
nix-env -i xplr-0.15.2 -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz   # file explorer
nix-env -i zellij-0.23.0 -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz # detachable sessions

# vs code extensions
code --install-extension jeff-hykin.swe-starter-pack
code --install-extension jeff-hykin.xd-theme
code --install-extension jeff-hykin.PKief.material-icon-theme