#!/usr/bin/env -S deno run --allow-all
const { run, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo, zipInto, mergeInto, returnAsString, } = await import(`https://deno.land/x/quickr@0.3.24/main/run.js`)
const { FileSystem } = await import(`https://deno.land/x/quickr@0.3.24/main/file_system.js`)


function extractLinesWithAddresses(string) {
    const addresses = string.split("\n").filter(each=>each.match(/(\d{1,3}\.)(\d{1,3}\.)+/))
    return addresses.join("\n")
}

// 
// run
// 
try {
    const ipDataString = await run("ifconfig", Stdout(returnAsString))
    console.log(extractLinesWithAddresses(ipDataString))
} catch (error) {
    const ipDataString = await run("ip", "address", Stdout(returnAsString))
    console.log(extractLinesWithAddresses(ipDataString))
}