#!/usr/bin/env bash

# summary
    # this only exists so that pip for-sure corrisponds to the python command

# if python exists
if [ -n "$(command -v "python")" ]
then
    python -m pip --disable-pip-version-check "$@"
else
    python3 -m pip --disable-pip-version-check "$@"
fi
