#!/usr/bin/env bash

# (assumes nix is installed)

install_mac_apps=false
if [ "$(uname)" = "Darwin" ] 
then
    question="install homebrew apps? [y/n]";answer=''
    while true; do
        echo "$question"; read response
        case "$response" in
            [Yy]* ) answer='yes'; break;;
            [Nn]* ) answer='no'; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
    
    if [ "$answer" = 'yes' ]; then
        install_mac_apps=true
    else
        install_mac_apps=false
    fi
    
fi

nix-env -iA alacritty -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz  
nix-env -iA vscode -f https://github.com/NixOS/nixpkgs/archive/bf972dc380f36a3bf83db052380e55f0eaa7dcb6.tar.gz
nix-env -iA nodePackages.ungit -f https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz  

# get nixGL (fixes alacritty on nvidia-driven stuf)
nix-channel --add https://github.com/guibou/nixGL/archive/main.tar.gz nixgl && nix-channel --update
nix-env -iA nixgl.auto.nixGLDefault   # or replace `nixGLDefault` with your desired wrapper

# vs code extensions
code --install-extension jeff-hykin.swe-starter-pack
code --install-extension jeff-hykin.xd-theme
code --install-extension jeff-hykin.mario
code --install-extension PKief.material-icon-theme
code --install-extension nmsmith89.incrementor
code --install-extension neptunedesign.vs-sequential-number

if [ "$install_mac_apps" = "true" ]
then
    # if brew doesnt exist, install it
    if [ -z "$(command -v "brew")" ]
    then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi
    
    brew install --cask flycut
    brew install --cask alt-tab
    brew install --cask aldente
    brew install --cask standard-notes
    brew install --cask telegram
    brew install --cask firefox
    
    brew install --cask xquartz
    brew install --cask visual-studio-code
    
    # brew install --cask rectangle
    
    brew install --cask nextcloud
    brew install --cask folx
    brew install --cask ipfs
    brew install --cask tor-browser
    brew install --cask arduino-ide
    brew install --cask chromium
    
    brew install --cask zotero
fi