#!/usr/bin/env bash

curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sudo sh -s -- install

# update the current shell env
if [ -f "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" ]
then
    . "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
fi
if [ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ]
then
    . "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi
export PATH="$PATH:/nix/var/nix/profiles/default/bin/"
export NIXPKGS_ALLOW_UNFREE=1