#!/usr/bin/env bash

# if apt-get exists and if curl not exists
if [ -n "$(command -v "apt-get")" ] && [ -n "$(command -v "curl")" ]
then
    sudo apt-get update -y 
    sudo apt-get install -y curl
fi

# install nix
. <(curl -fsSL https://raw.githubusercontent.com/jeff-hykin/home/master/Commands/setup_nix)
# install git
nix-env -iA nixpkgs.git

# setup home
. <(curl -fsSL https://raw.githubusercontent.com/jeff-hykin/home/master/Commands/setup_home)

# install all the basics with nix
. <(curl -fsSL https://raw.githubusercontent.com/jeff-hykin/home/master/Commands/setup_basic_cli_stuff || wget -qO- https://raw.githubusercontent.com/jeff-hykin/home/master/Commands/setup_basic_cli_stuff)