#!/usr/bin/env -S deno run --allow-all
const { run, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo, zipInto, mergeInto, returnAsString, } = await import(`https://deno.land/x/sprinter@0.4.2/index.js`)
const { FileSystem, Console } = await import(`https://deno.land/x/file_system_js@0.5.1/main/deno.js`)

const sshFolder = `${FileSystem.home}/.ssh/`
const authorizedKeysPath = `${FileSystem.home}/.ssh/authorized_keys`
const defaultPrivateKeyPath = `${sshFolder}/id_rsa`
const defaultPublicKeyPath = `${sshFolder}/id_rsa.pub`
const configPath = `${sshFolder}/config`

// 
// 
// main 
// 
// 
await verifyAndSetupSshFolderStructure()
console.log(`

    __________________      __________________
    | "Your" Machine |  ->  | Remote Machine | 
    ------------------      ------------------  

`)
if (await Console.askFor.yesNo("Is this script running on your machine right now?")) {
    await ensurePrivatePublicRsaKeyExists()
    console.log("Now run this same script on the remote server (on your account)")
    console.log("Paste the value below when it asks for your public key")
    console.log("(and FYI you can show this to anyone, its not private)")
    console.log()
    Console.bgBlack.blue(await FileSystem.read(defaultPublicKeyPath)).log()
    console.log()
    console.log()
} else {
    let publicKeyString = ""
    while (publicKeyString.length == 0) {
        publicKeyString = await Console.askFor.line(`Whats the public key of your machine?\n(run this script on your machine to get it)`)
    }
    await FileSystem.append({
        path: authorizedKeysPath,
        data: publicKeyString+"\n",
    })
    // TODO: assumes debian/ubuntu
    if (await Console.askFor.yesNo(`Would you like to restart ssh to make the change take effect?`)) {
        await run("sudo", "systemctl", "restart", "ssh.service")
    }
}

function escapeShellArgument(string) {
    return `'${string.replace(/'/,`'"'"'`)}'`
}

async function ensurePrivatePublicRsaKeyExists() {
    let privateKey = await FileSystem.info(defaultPrivateKeyPath)
    let publicKey = await FileSystem.info(defaultPublicKeyPath)
    while (!privateKey.isFile || !publicKey.isFile) {
        console.log("\nLooks like your private key doesn't exist so lets make one")
        Console.bgBlack.white("    running: ").bgBlack.blue("ssh-keygen -t rsa").log()
        await run("ssh-keygen", "-t", "rsa", "-f", defaultPrivateKeyPath)
        privateKey = await FileSystem.info(defaultPrivateKeyPath)
        publicKey = await FileSystem.info(defaultPublicKeyPath)
    }
}

async function getFingerprint(path=defaultPublicKeyPath) {
    return run("ssh-keygen", "-lf", path, Stdout(returnAsString))
}

async function verifyAndSetupSshFolderStructure() {
    await FileSystem.ensureIsFolder(sshFolder)
    const authInfo = await FileSystem.info(authorizedKeysPath)
    if (!authInfo.exists) {
        await Deno.writeTextFile(authorizedKeysPath, "")
    }
    // following: https://superuser.com/a/925859/399438

    // SSH folder on the server needs 700 permissions: chmod 700 $HOME/.ssh
    await FileSystem.addPermissions({
        path: sshFolder,
        permissions: {
            owner:{
                canRead: true,
                canWrite: true,
                canExecute: true,
            }, 
            group:{
                canRead: false,
                canWrite: false,
                canExecute: false,
            },
            others:{
                canRead: false,
                canWrite: false,
                canExecute: false,

            }
        },
    })
    
    // sudo chmod 600 ~/.ssh/config
    const configInfo = await FileSystem.info(configPath)
    if (configInfo.doesntExist) {
        await FileSystem.write({
            data: `# Read more about SSH config files: https://linux.die.net/man/5/ssh_config\n# Host alias\n#     HostName hostname\n#     User user\n`,
            path: configPath,
        })
    }
    await FileSystem.addPermissions({
        path: configPath,
        permissions: {
            owner:{
                canRead: true,
                canWrite: true,
                canExecute: false,
            }, 
            group:{
                canRead: false,
                canWrite: false,
                canExecute: false,
            },
            others:{
                canRead: false,
                canWrite: false,
                canExecute: false,

            }
        },
    })
    const permissions = await FileSystem.getPermissions({path: configPath,})

    // authorized_keys file needs 644 permissions: chmod 644 $HOME/.ssh/authorized_keys
    await FileSystem.addPermissions({
        path: authorizedKeysPath,
        permissions: {
            owner:{
                canRead: true,
                canWrite: true,
                canExecute: false,
            }, 
            group:{
                canRead: true,
                canWrite: false,
                canExecute: false,
            },
            others:{
                canRead: true,
                canWrite: false,
                canExecute: false,

            }
        },
    })
    // Make sure that user owns the files/folders and not root: chown user:user authorized_keys and chown user:user /home/$USER/.ssh
    const username = (await run("whoami", Stdout(returnAsString))).trim()
    const userId = (await run("id", "-u", username, Stdout(returnAsString))).trim()
    const { uid } = await Deno.lstat(sshFolder)
    if (`${userId}` !== `${uid}`) {
        console.log(`\nFor some reason you're not the owner of your own home/.ssh/ folder (strange)`)
        console.log(`    your  username: ${username}`)
        // console.log(`    owner username: ${fileOwner}`) // currently don't have folder owner name
        console.log(`Lets change that:\n`)
        await run("sudo", "chown", username, sshFolder)
    }
}