#!/usr/bin/env bash
if [ "$OSTYPE" = "linux-gnu" ] 
then
    # if apt exists
    if [ -n "$(command -v "apt")" ]
    then
        sudo apt update
        sudo apt install -y openssh-server
        sudo ufw allow ssh
        sudo systemctl enable --now ssh
        sudo systemctl enable ssh
        sudo systemctl start ssh
    else
        echo "sorry not sure how to do it if you don't have apt"
    fi
fi